flags: {}
extra-package-dbs: []
packages:
- location: '.'
- location: ./pkgs/idna-hs/
- location: ./pkgs/dns/
extra-deps:
- stringprep-1.0.0
- punycode-2.0
- optparse-applicative-0.14.3.0
resolver: lts-9.21
ghc-options:
    "$locals": -Wall
    "$everything": -O2
